import type { ExplainText } from './explain.ts';
import type { Category } from './scan.ts';

export const ADMIN_TEXT: Partial<Record<Category, ExplainText>> = {
  'system-temp': { what: 'Files in C:\\Windows\\Temp that nobody has modified for over 24 hours.', why: 'Installers and Windows services leave scratch files here. Only files directly in the folder are removed; subfolders and anything in use are skipped.', after: 'PERMANENT, not quarantined. Needs administrator approval (a Windows UAC prompt).' },
  'windows-update': { what: 'Update packages Windows Update already downloaded (SoftwareDistribution\\Download).', why: 'Windows keeps downloads after installing them. Hydra-bane stops the Windows Update and BITS services, empties the folder, and starts the services again if they were running.', after: 'PERMANENT. Windows downloads again anything it still needs, so a pending update may download twice. Needs administrator approval.' },
  'delivery-optimization': { what: 'Update files Windows keeps to share with other PCs (Delivery Optimization cache).', why: 'Cleared with `Delete-DeliveryOptimizationCache`, the official Windows command.', after: 'PERMANENT. Nothing breaks; Windows refills the cache over time. Needs administrator approval.' },
  'system-dumps': { what: 'Memory dumps Windows wrote after a blue screen (MEMORY.DMP and the Minidump folder).', why: 'They only help if you or a technician want to find out why the PC crashed.', after: 'PERMANENT. You can no longer analyse those crashes. Needs administrator approval.' },
  'wer-archive': { what: 'Old Windows Error Reporting reports (ReportArchive and ReportQueue).', why: 'Windows keeps crash reports it already sent or will never send. Your account may delete them, so no administrator approval is used here on purpose: other users can write into these folders.', after: 'PERMANENT. The crash history in Reliability Monitor gets shorter.' },
  winsxs: { what: 'Old versions of Windows components replaced by updates (the WinSxS component store).', why: 'Cleaned with `DISM /Online /Cleanup-Image /StartComponentCleanup`, the official Windows command. The more aggressive /ResetBase is never used. The size is only known after DISM analyses the store, which needs administrator rights.', after: 'PERMANENT. Updates installed so far can no longer be uninstalled back to those older versions. It can take many minutes. Needs administrator approval.' },
  hibernation: { what: 'The hibernation file C:\\hiberfil.sys, which is about as big as a large part of your RAM.', why: 'Hydra-bane runs `powercfg /hibernate off`, the official command; Windows deletes the file itself.', after: 'Hibernate stops working AND Fast Startup is turned off, so a cold boot may take a bit longer. Not undoable by Hydra-bane, but `powercfg /hibernate on` (as administrator) turns it back on and recreates the file. Needs administrator approval.' },
  'windows-old': { what: 'The previous Windows installation kept after a Windows upgrade (C:\\Windows.old).', why: 'Only Windows itself should remove it, so Hydra-bane only reports it and tells you where to click.', after: 'Removing it in Settings is PERMANENT: you can no longer roll back to the previous Windows version. Needs administrator rights.' },
  'wsl-disk': { what: 'The virtual disk of a WSL Linux distribution (ext4.vhdx).', why: 'The file grows but never shrinks on its own. Hydra-bane runs `wsl --manage <distro> --set-sparse true`, the official command, and never touches the file directly. No administrator approval needed.', after: 'Space freed inside Linux returns to Windows from then on, gradually; the size shown is the file, not a promise. The distro must not be running (`wsl --shutdown` first). `--set-sparse false` turns it off again. Some WSL versions refuse it pending a data-safety fix; then nothing changes.' },
  'docker-disk': { what: 'The virtual disk where Docker Desktop keeps images, containers, volumes and build cache.', why: 'Deleting inside Docker has to be done by Docker. Volumes are your data, so Hydra-bane only reports this and gives the steps.', after: 'Nothing happens until you follow the steps yourself. `docker system prune` removes unused containers, images and cache; pruning volumes deletes data for good.' },
};
