import type { ExplainText } from './explain.ts';
import type { Category } from './scan.ts';

export const CACHE_TEXT_V02: Partial<Record<Category, ExplainText>> = {
  'yarn-cache': { what: 'Packages yarn downloaded before.', why: 'yarn keeps a copy of every package it fetched. Projects already installed do not read from it. Hydra-bane runs `yarn cache clean`.', after: 'yarn downloads packages again the next time a project installs them.' },
  'bun-cache': { what: 'Packages bun downloaded before.', why: 'bun keeps a global package cache to speed up installs. Hydra-bane runs `bun pm cache rm`.', after: 'bun downloads packages again on the next install.' },
  'conda-pkgs': { what: 'Downloaded conda packages and tarballs in the pkgs folder.', why: '`conda clean --all` removes tarballs, index caches and packages no environment uses. Your environments keep working.', after: 'conda downloads packages again if a new environment needs them. The size shown is the most it can free, because packages still used by environments stay.' },
  'poetry-cache': { what: "Poetry's cached package information from PyPI.", why: 'Only the PyPI cache is cleared with `poetry cache clear --all pypi`. Poetry virtualenvs in the same folder are not touched.', after: 'Poetry fetches package information again on the next lock or install, which is a little slower once.' },
  'go-cache': { what: 'Go build results (GOCACHE) or downloaded Go modules (GOMODCACHE).', why: 'Cleared with `go clean -cache` or `go clean -modcache`, the official commands. Your source code is elsewhere.', after: 'The next build compiles from scratch, or modules download again. It takes longer once.' },
  'nuget-cache': { what: 'NuGet packages and HTTP responses cached by .NET.', why: 'Cleared with `dotnet nuget locals <kind> --clear`, the official command. Projects restore what they need.', after: 'The next `dotnet restore` or build downloads packages again.' },
  'gradle-cache': { what: 'Caches or wrapper downloads of an older Gradle version, when a newer one is present.', why: 'Each Gradle version keeps its own folder, and old ones stay after upgrades. Shared dependency caches are not touched.', after: 'A project still pinned to that old version downloads it again on its next build. If a Gradle daemon of that version is running, run `gradle --stop` first; locked files make this item fail rather than half-finish silently.' },
  'maven-repo': { what: 'Versions of Maven dependencies that nothing has read or changed for 90+ days.', why: 'Maven never removes old versions. Only folders Maven downloaded from a remote repository are offered; artifacts you built and installed locally are kept.', after: 'Maven downloads them again when a build needs them. An offline build (`mvn -o`) that needs one fails until you are online once.' },
  'hf-models': { what: 'A model downloaded by HuggingFace libraries (transformers, diffusers, hf CLI).', why: 'The hub cache keeps every model you ever loaded. Only this model folder is removed; other models and your own files are not touched.', after: 'The model is downloaded again the next time code loads it. Large models can take a long time to download.' },
  leftovers: { what: 'A folder, Start Menu shortcut or registry key left behind by a program Hydra-bane uninstalled earlier. It carries exactly that program\'s name.', why: 'Only programs Hydra-bane removed itself, and that are no longer installed, are checked. Folders holding a git repository are never offered; folders with several documents or pictures, machine-wide folders and HKLM keys are only reported.', after: 'Folders and shortcuts are moved to quarantine (undo for 7 days). A registry key is first exported into the quarantine, then deleted; undo imports the export back.' },
  installers: { what: 'An installer file (.exe, .msi, .msix/.appx, .iso, .dmg, .pkg, or a .zip whose name says setup/install/portable, or an architecture plus a version) lying directly in your Downloads folder, unchanged for 30+ days.', why: 'Installers are usually needed once. Only the top level of Downloads is checked, never subfolders; files that are open or running are skipped. Each file is its own item and apply may move only that file. .img files are only reported, because they can be disk backups you made.', after: 'The file is moved to quarantine (undo for 7 days). Download it again from the vendor if you need it later.' },
  orphans: { what: 'A folder in %LOCALAPPDATA%\Programs that holds a program but that no installed program, Start Menu shortcut or startup entry points to, or Start Menu shortcuts whose target no longer exists.', why: 'Programs removed without their uninstaller (or deleted by hand) leave these behind. Folders must be unchanged for 30+ days; git repositories are never offered, and folders with several documents or too many files are only reported. Folders in AppData without a program are never offered, because a name alone cannot prove which program owned them.', after: 'Moved to quarantine (undo for 7 days). If a program in that folder was still in use, undo brings it back unchanged.' },
  'ollama-models':{ what: 'A model installed in Ollama.', why: 'Removed with `ollama rm`, so Ollama itself decides which files go. Parts shared with other models stay. Ollama must be running.', after: 'Run `ollama pull <model>` to get it back. Large models can take a long time to download.' },
};
